<?php
return array(
	'user' => 'CURRENT_DATE_TIME, CURRENT_DATE, NAME, USERNAME, EMAIL,DATE_OF_BIRTH, DESIGNATION, DEPARTMENT', 
	'task' => 'NAME, USERNAME, EMAIL, DESIGNATION, DEPARTMENT, TASK_TITLE, TASK_CATEGORY, TASK_PRIORITY, TASK_START_DATE, TASK_DUE_DATE, TASK_OWNER_NAME, TASK_OWNER_EMAIL, TASK_OWNER_DESIGNATION, TASK_OWNER_DEPARTMENT, CURRENT_DATE_TIME, CURRENT_DATE', 
	);